### ISSUE TITLE
[Bug] Wrong output when converting between hex and int format

### ISSUE THREAD

**Issue by havspect** [isaacbrodsky/h3-duckdb#10]
I found the following bug when translating between the h3 hex and int format. It would be great if you can fix the bug or supply me with information about my wrongdoing. 

![image](https://user-images.githubusercontent.com/54222112/218424511-22c156df-f713-4a6f-a35d-7e2ab438f9c4.png)

Details: 
- The representation of the resulting string has the wrong format 
- The referenced h3Index ("85283473fffffff") should point to (37.34579337536848, -121.9763759725512)

**Comment by havspect** [comment]
After some further research, I think the problem is the representation in a numeric format. The results become correct when adding a trailing “0” to each number. However, this cannot be done for the remaining functions, since the results are cast in an ubigint format.

**Comment by isaacbrodsky** [comment]
Hi, sorry I missed this report. I am making a PR to fix the returned coordinates (it is returning radians instead of degrees as intended, as with #14.)

I was not able to reproduce the issue shown above with `h3_h3_to_string`:

```
D select h3_h3_to_string(599686042433355775::ubigint);
┌──────────────────────────────────────────────────────┐
│ h3_h3_to_string(CAST(599686042433355775 AS UBIGINT)) │
│                       varchar                        │
├──────────────────────────────────────────────────────┤
│ 85283473fffffff                                      │
└──────────────────────────────────────────────────────┘
D select h3_h3_to_string(cast(599686042433355775 as ubigint));
┌──────────────────────────────────────────────────────┐
│ h3_h3_to_string(CAST(599686042433355775 AS UBIGINT)) │
│                       varchar                        │
├──────────────────────────────────────────────────────┤
│ 85283473fffffff                                      │
└──────────────────────────────────────────────────────┘
```

Could you let me know, if this is still an issue, what operating system, version of DuckDB & this extension, and CPU architecture you are using?

**Comment by havspect** [comment]
Hi @isaacbrodsky, 
the h3_h3_to_string() error can be reproduced on multiple machines running both intel and AMD personal and business CPUs. The operating system was Ubuntu Linux and the v0.6 duckdb version.

**Comment by havspect** [comment]
Ah, and thank you for the great work and quick fix!
