### ISSUE TITLE
Offline install / not https access

### ISSUE THREAD

**Issue by bevanward** [isaacbrodsky/h3-duckdb#109]
Is it possible to add a method to install offline?

This options worked previously
install 'h3ext.duckdb_extension';

However without https access this doesn't work
INSTALL h3ext FROM 'https://pub-cc26a6fd5d8240078bd0c2e0623393a5.r2.dev';

Downloading manually the spatial extension - spatial.duckdb_extension
means it can be installed offline.

Thanks
Bevan

**Comment by bward0001** [comment]
Thanks @isaacbrodsky turned out I was missing the C redistributable.
