### ISSUE TITLE
h3_grid_ring_unsafe breaks when running on data set

### ISSUE THREAD

**Issue by fhk** [isaacbrodsky/h3-duckdb#120]
~~When running ```h3_latlng_to_cell``` it is possible to swap x, and y.~~

~~This means that values outside the range when swapped~~

~~-90 <-> 90 and -180 <-> 180~~

~~This leads to NULL values breaking downstream silently~~

**Comment by fhk** [comment]
```bash
!./duckdb -unsigned -c "\
  SET threads TO 8; \
  SET memory_limit = '50GB'; \
  LOAD SPATIAL; \
  LOAD H3; \
  WITH \
  layer AS (SELECT ST_POINT(x, y) as geom, h3_latlng_to_cell(y, x, 5) as h3_5 FROM READ_CSV('./Substations.csv')), \
  k_rings AS (SELECT CAST(i AS INTEGER) as i FROM range(1, 100, 1) t1(i)),\
  explode AS (SELECT DISTINCT h3_5, i FROM k_rings CROSS JOIN layer)\
  SELECT h3_5 as h3_5_src, h3_grid_ring_unsafe(h3_5, i) as h3_dst, i FROM explode"
  ```

**Comment by fhk** [comment]
Ok this looks to be caused when the inputs are Nan (empty) in a csv

**Comment by isaacbrodsky** [comment]
This is related to #35 -- do you except null inputs to result in null outputs? or so some other output?

**Comment by fhk** [comment]
Not sure what the philosophy of duckdb is on validation.

I can see arguments for both fail fast on input and null pass through.

At the moment it would appear that some other things break on null and it’s not clear where or why.

So perhaps being strict is OK?
