### ISSUE TITLE
v1.1.1 pre-built binaries ready?

### ISSUE THREAD

**Issue by marklit** [isaacbrodsky/h3-duckdb#131]
I'm running v1.1.1 af39bd0dcf on Ubuntu for Windows.

```bash
$ ~/duckdb_111/duckdb
```

```sql
INSTALL h3 FROM community;
```

```
HTTP Error: Failed to download extension "h3" at URL "http://community-extensions.duckdb.org/v1.1.1/linux_amd64_gcc4/h3.duckdb_extension.gz" (HTTP 403)

Candidate extensions: "s3", "http", "https", "httpfs", "motherduck"
```

**Comment by carlopi** [comment]
Community extension are being build at this moment.

We have a plan in place to improve this and build also community extensions in advance, but as of today it's a process kicked off after release is tagged, and a few hours for all extensions to be there.

**Comment by marklit** [comment]
Great, got it installed here. Thank you.
