### ISSUE TITLE
Bind all region functions

### ISSUE THREAD

**Issue by isaacbrodsky** [isaacbrodsky/h3-duckdb#24]
https://h3geo.org/docs/api/regions

**Comment by carstonhernke** [comment]
Hi Issac, I'm interested in using some of the region functions in DuckDB, especially `polygonToCells()`. Let me know if I can lend a hand getting the bindings put together.

**Comment by isaacbrodsky** [comment]
What input form would be most helpful for `polygonToCells`? WKT?

**Comment by carstonhernke** [comment]
WKT would be great. Longer-term, it would be cool to use Polygon columns from the DuckDB Spatial Extension directly (https://duckdb.org/docs/extensions/spatial.html).

**Comment by carstonhernke** [comment]
Fantastic!
