### ISSUE TITLE
Building extension in windows 64 bit

### ISSUE THREAD

**Issue by lebuu-eu** [isaacbrodsky/h3-duckdb#32]
I am getting this error when I am trying to build the bindings in my Windows operating system. When I tried to build the extension, I got this error. 
I am not an expert on building extensions, but I couldn’t find any solution.
I am running on Windows 64-bit operating system.
Thanks. 
![build_tpch_issue](https://github.com/isaacbrodsky/h3-duckdb/assets/12136899/7b8da2aa-8e54-426c-a3f2-b2cf98485173)

**Comment by Joaquin-Urruti** [comment]
God! I'm getting the same error... tryed infinite solutions and nothing seems to work...

**Comment by isaacbrodsky** [comment]
In CI, this is tested on PowerShell, not cmd. You may need to use PowerShell or Bash (usually installed when you install Git) to build h3-duckdb.
 (I haven't had a chance to test building on a real Windows machine yet)

**Comment by Joaquin-Urruti** [comment]
I'll try it out, thanks!

**Comment by Joaquin-Urruti** [comment]
In Powershell didn't work either...

**Comment by Joaquin-Urruti** [comment]
tryed WSL couldn't make it work either...

**Comment by isaacbrodsky** [comment]
I tried this today and was not able to get it to work on `main`. After updating the build system to match sqlite_scanner again, it seems to be building on Windows. I also had to upgrade duckdb in order to use the new build code. Code is in #66.

I sued VS2019 and also installed the following:

```cmd
choco install cmake.install --installargs '"ADD_CMAKE_TO_PATH=System"'
choco install make
```

(Note: You may need to reopen any shells after running the above.)

Then, to build, from Git Bash:
```sh
make debug
```

Test:
```sh
./build/debug/Debug/duckdb.exe -unsigned -interactive
```
```sql
load 'build\debug\extension\h3ext\h3ext.duckdb_extension';
select h3_h3_to_string(h3_latlng_to_cell(0,0,0));
```

**Comment by isaacbrodsky** [comment]
The latest version of the extension should build on Windows, using the following command:

```
CMAKE_BUILD_PARALLEL_LEVEL=8 make release
```
