### ISSUE TITLE
Add cellToBoundary binding

### ISSUE THREAD

**Issue by isaacbrodsky** [isaacbrodsky/h3-duckdb#45]

**Comment by marklit** [comment]
This would be very useful. Exportings cells as geom fields into GPKG files would allow single SQL statements to produce files that open in QGIS for visualisation with no intermediate steps.

**Comment by isaacbrodsky** [comment]
@marklit (and anyone else who wants to chime in)

What format would you expect the output of cellToBoundary to be? List of coordinates? WKB? DuckDB's geometry type (not sure if this extension can produce that without making DuckDB Spatial a dependency)?

**Comment by marklit** [comment]
Maybe just a WKT polygon?

**Comment by marklit** [comment]
Fantastic, thank you very much!

**Comment by marklit** [comment]
Should longitude come before latitude to be ESPG:4326 compliant?

```sql
SELECT (
           UNNEST(
               H3_CELL_TO_CHILDREN(
                   H3_LATLNG_TO_CELL(24.75,
                                     59.44,
                                     6), 9))) geom
LIMIT 1;
```

```
POLYGON ((59.419882 24.753254, 59.421048 24.751824, 59.423026 24.751898,
```
