### ISSUE TITLE
Recent main trunk core dump on linux

### ISSUE THREAD

**Issue by akhenakh** [isaacbrodsky/h3-duckdb#76]
duckdb -unsigned                                                                                                                       
v0.9.2 3c695d7ba9
Enter ".help" for usage hints.
D load h3ext;
[1]    133840 floating point exception (core dumped)  duckdb -unsigned

x86_64 GNU/Linux 

release build

(same commit works on Mac OSX)

**Comment by isaacbrodsky** [comment]
Unfortunately I am not able to reproduce this in my test system. Could you retry with debugging symbols enabled and post a stack trace? Could you post what compiler you used?

**Comment by akhenakh** [comment]
@isaacbrodsky  update to upstream solved the Linux issue 

https://github.com/akhenakh/h3-duckdb/commit/279b1598845c620ecdff9e2bd7f67e7de1571f98

**Comment by isaacbrodsky** [comment]
@akhenakh Great to hear!

**Comment by isaacbrodsky** [comment]
Please try again with v0.10.0 and let me know if it is still an issue

**Comment by akhenakh** [comment]
solved thanks!
