### ISSUE TITLE
build question

### ISSUE THREAD

**Issue by wxinl** [isaacbrodsky/h3-duckdb#77]
I tried to follow the readme to install the h3 extension. However I failed at running `CMAKE_BUILD_PARALLEL_LEVEL=4 make duckdb_release release` at the terminal, which gives me the error `'CMAKE_BUILD_PARALLEL_LEVEL' is not recognized as an internal or external command, operable program or batch file.`

I have cmake 3.13.1 installed, and my system is windows 11

**Comment by isaacbrodsky** [comment]
You may try running with `make duckdb_release release` which will just not configure the build parallelism. You are getting that error because the syntax is for a UNIX shell (such as Git Bash, which you may already have installed) but you are entering it on a Windows command prompt.
